
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Tue May 26 13:53:37 CEST 2020
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "setInfo", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setInfo", namespace = "http://service/")

public class SetInfo {

    @XmlElement(name = "info")
    private model.Course info;

    public model.Course getInfo() {
        return this.info;
    }

    public void setInfo(model.Course newInfo)  {
        this.info = newInfo;
    }

}

