
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Tue May 26 13:53:37 CEST 2020
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "setInfoResponse", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setInfoResponse", namespace = "http://service/")

public class SetInfoResponse {


}

